function (%%cpp_init_replace%%_target_always_include target acc file)
    if (MSVC)
        target_compile_options(${target} ${acc} "/FI${file}")
    else ()
        target_compile_options(${target} ${acc} "-include${file}")
    endif ()
endfunction ()
