include("${PROJECT_SOURCE_DIR}/cmake/helpers.cmake")
function (%%cpp_init_replace%%_target_enable_sanitizers target acc)
    if (MSVC OR NOT %%CPP_INIT_REPLACE%%_ENABLE_SANITIZERS)
        return()
    endif ()

    _%%cpp_init_replace%%_normalise_val(%%CPP_INIT_REPLACE%%_ENABLE_SANITIZERS _normal)

    if (_normal STREQUAL LIST)
        list(JOIN %%CPP_INIT_REPLACE%%_ENABLE_SANITIZERS ">,$<CONFIG:" _joined)
        set(_joined "$<OR:$<CONFIG:${_joined}>>")
        set(_arg $<${_joined}:-fsanitize=${%%CPP_INIT_REPLACE%%_SANITIZER_LIST}>)
        list(JOIN %%CPP_INIT_REPLACE%%_ENABLE_SANITIZERS ", ${target}:" _target_name)
        set(_target_name "${target}:${_target_name}")
    else ()
        set(_arg -fsanitize=${%%CPP_INIT_REPLACE%%_SANITIZER_LIST})
        set(_target_name "${target}")
    endif ()

    message(STATUS "Configured ${_target_name} with sanitizers: [${%%CPP_INIT_REPLACE%%_SANITIZER_LIST}]")
    target_compile_options(${target} ${acc} ${_arg})
    target_link_options(${target} ${acc} ${_arg})
endfunction ()
